apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql-order
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mysql-order
  template:
    metadata:
      labels:
        app: mysql-order
    spec:
      containers:
        - name: mysql-order
          image: mysql:8
          ports:
            - containerPort: 3306
          env:
            - name: MYSQL_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: order-db-secret
                  key: SPRING_DATASOURCE_PASSWORD
            - name: MYSQL_DATABASE
              value: ordersdb
          volumeMounts:
            - name: mysql-order-storage
              mountPath: /var/lib/mysql
      volumes:
        - name: mysql-order-storage
          emptyDir: {}

