apiVersion: v1
kind: ConfigMap
metadata:
  name: order-db-config
data:
  SPRING_DATASOURCE_URL: jdbc:mysql://mysql-order:3306/ordersdb
  SPRING_DATASOURCE_USERNAME: root
  SPRING_DATASOURCE_DRIVER_CLASS_NAME: com.mysql.cj.jdbc.Driver
